<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Task Completed</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            margin-bottom: 20px;
        }
        .content {
            background-color: #ffffff;
            padding: 20px;
            border: 1px solid #dee2e6;
            border-radius: 8px;
        }
        .box-info {
            background-color: #e9ecef;
            padding: 15px;
            border-radius: 5px;
            margin: 15px 0;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            color: #6c757d;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🎉 Task Completed Successfully!</h1>
    </div>
    
    <div class="content">
        <h2>Hello {{ $fullName }},</h2>
        
        <p>Congratulations! Your box scheduler task has been completed successfully.</p>
        
        <div class="box-info">
            <h3>Task Summary:</h3>
            <ul>
                <li><strong>Total Boxes Created:</strong> {{ $boxCount }}</li>
                <li><strong>Box Dimensions:</strong> 40px height × 100px width</li>
                <li><strong>Colors Used:</strong> Red, Yellow, Green, Blue, Pink, Grey</li>
                <li><strong>Completion Time:</strong> {{ now()->format('Y-m-d H:i:s') }}</li>
            </ul>
        </div>
        
        <p>The scheduler has successfully:</p>
        <ul>
            <li>Started with 1 box</li>
            <li>Doubled the number of boxes every minute</li>
            <li>Stored all box data in the database using Eloquent</li>
            <li>Stopped when reaching {{ $boxCount }} boxes</li>
            <li>Sent this completion notification</li>
        </ul>
        
        <p>Thank you for using the Box Scheduler system!</p>
        
        <p>Best regards,<br>
        <strong>{{ $fullName }}</strong></p>
    </div>
    
    <div class="footer">
        <p>This email was automatically generated by the Box Scheduler system.</p>
        <p>Generated on {{ now()->format('F j, Y \a\t g:i A') }}</p>
    </div>
</body>
</html>
